/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsEnum } from "class-validator";
import { ProductSpuInfoUpdateManyWithoutSupplierInfosInput } from "./ProductSpuInfoUpdateManyWithoutSupplierInfosInput";
import { Type } from "class-transformer";
import { EnumSupplierInfoSupplierStatus } from "./EnumSupplierInfoSupplierStatus";
@InputType()
class SupplierInfoUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bankAccount?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bankName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  linkMan?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProductSpuInfoUpdateManyWithoutSupplierInfosInput,
  })
  @ValidateNested()
  @Type(() => ProductSpuInfoUpdateManyWithoutSupplierInfosInput)
  @IsOptional()
  @Field(() => ProductSpuInfoUpdateManyWithoutSupplierInfosInput, {
    nullable: true,
  })
  productSupplierId?: ProductSpuInfoUpdateManyWithoutSupplierInfosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  supplierCode?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  supplierName?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumSupplierInfoSupplierStatus,
  })
  @IsEnum(EnumSupplierInfoSupplierStatus)
  @IsOptional()
  @Field(() => EnumSupplierInfoSupplierStatus, {
    nullable: true,
  })
  supplierStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  supplierType?: string | null;
}
export { SupplierInfoUpdateInput };
