/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsEnum, ValidateNested } from "class-validator";
import { EnumProductCategoryCategoryStatus } from "./EnumProductCategoryCategoryStatus";
import { ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput } from "./ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput";
import { Type } from "class-transformer";
@InputType()
class ProductCategoryCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  categoryCode?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  categoryLevel?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  categoryName?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumProductCategoryCategoryStatus,
  })
  @IsEnum(EnumProductCategoryCategoryStatus)
  @IsOptional()
  @Field(() => EnumProductCategoryCategoryStatus, {
    nullable: true,
  })
  categoryStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  parentId?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput,
  })
  @ValidateNested()
  @Type(() => ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput)
  @IsOptional()
  @Field(() => ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput, {
    nullable: true,
  })
  productOneCategoryId?: ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput,
  })
  @ValidateNested()
  @Type(() => ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput)
  @IsOptional()
  @Field(() => ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput, {
    nullable: true,
  })
  productThreeCategoryId?: ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput,
  })
  @ValidateNested()
  @Type(() => ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput)
  @IsOptional()
  @Field(() => ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput, {
    nullable: true,
  })
  productTwoCategoryId?: ProductSpuInfoCreateNestedManyWithoutProductCategoriesInput;
}
export { ProductCategoryCreateInput };
