/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";

import {
  Prisma,
  ProductSPUInfo,
  ProductPicInfo,
  BrandInfo,
  ProductCategory,
  SupplierInfo,
} from "@prisma/client";

export class ProductSPUInfoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.ProductSPUInfoFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductSPUInfoFindManyArgs>
  ): Promise<number> {
    return this.prisma.productSpuInfo.count(args);
  }

  async findMany<T extends Prisma.ProductSPUInfoFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductSPUInfoFindManyArgs>
  ): Promise<ProductSPUInfo[]> {
    return this.prisma.productSpuInfo.findMany(args);
  }
  async findOne<T extends Prisma.ProductSPUInfoFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductSPUInfoFindUniqueArgs>
  ): Promise<ProductSPUInfo | null> {
    return this.prisma.productSpuInfo.findUnique(args);
  }
  async create<T extends Prisma.ProductSPUInfoCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductSPUInfoCreateArgs>
  ): Promise<ProductSPUInfo> {
    return this.prisma.productSpuInfo.create<T>(args);
  }
  async update<T extends Prisma.ProductSPUInfoUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductSPUInfoUpdateArgs>
  ): Promise<ProductSPUInfo> {
    return this.prisma.productSpuInfo.update<T>(args);
  }
  async delete<T extends Prisma.ProductSPUInfoDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductSPUInfoDeleteArgs>
  ): Promise<ProductSPUInfo> {
    return this.prisma.productSpuInfo.delete(args);
  }

  async findPicInfoProductId(
    parentId: string,
    args: Prisma.ProductPicInfoFindManyArgs
  ): Promise<ProductPicInfo[]> {
    return this.prisma.productSpuInfo
      .findUnique({
        where: { id: parentId },
      })
      .picInfoProductId(args);
  }

  async getBrandId(parentId: string): Promise<BrandInfo | null> {
    return this.prisma.productSpuInfo
      .findUnique({
        where: { id: parentId },
      })
      .brandId();
  }

  async getOneCategoryId(parentId: string): Promise<ProductCategory | null> {
    return this.prisma.productSpuInfo
      .findUnique({
        where: { id: parentId },
      })
      .oneCategoryId();
  }

  async getSupplierId(parentId: string): Promise<SupplierInfo | null> {
    return this.prisma.productSpuInfo
      .findUnique({
        where: { id: parentId },
      })
      .supplierId();
  }

  async getThreeCategoryId(parentId: string): Promise<ProductCategory | null> {
    return this.prisma.productSpuInfo
      .findUnique({
        where: { id: parentId },
      })
      .threeCategoryId();
  }

  async getTwoCategoryId(parentId: string): Promise<ProductCategory | null> {
    return this.prisma.productSpuInfo
      .findUnique({
        where: { id: parentId },
      })
      .twoCategoryId();
  }
}
