/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  IsOptional,
  IsNumber,
  IsString,
  ValidateNested,
  IsDate,
} from "class-validator";
import { BrandInfo } from "../../brandInfo/base/BrandInfo";
import { Type } from "class-transformer";
import { ProductCategory } from "../../productCategory/base/ProductCategory";
import { ProductPicInfo } from "../../productPicInfo/base/ProductPicInfo";
import { SupplierInfo } from "../../supplierInfo/base/SupplierInfo";
@ObjectType()
class ProductInfo {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  auditStatus!: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  averageCost!: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  barCode!: string | null;

  @ApiProperty({
    required: false,
    type: () => BrandInfo,
  })
  @ValidateNested()
  @Type(() => BrandInfo)
  @IsOptional()
  brandId?: BrandInfo | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descript!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => ProductCategory,
  })
  @ValidateNested()
  @Type(() => ProductCategory)
  @IsOptional()
  oneCategoryId?: ProductCategory | null;

  @ApiProperty({
    required: false,
    type: () => [ProductPicInfo],
  })
  @ValidateNested()
  @Type(() => ProductPicInfo)
  @IsOptional()
  picInfoProductId?: Array<ProductPicInfo>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price!: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  productCore!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  productDetail!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  productionDate!: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  productKeywords!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  productName!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  productSubtitle!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  publishStatus!: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  purchasePrice!: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  qrCode!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  shelfLife!: number | null;

  @ApiProperty({
    required: false,
    type: () => SupplierInfo,
  })
  @ValidateNested()
  @Type(() => SupplierInfo)
  @IsOptional()
  supplierId?: SupplierInfo | null;

  @ApiProperty({
    required: false,
    type: () => ProductCategory,
  })
  @ValidateNested()
  @Type(() => ProductCategory)
  @IsOptional()
  threeCategoryId?: ProductCategory | null;

  @ApiProperty({
    required: false,
    type: () => ProductCategory,
  })
  @ValidateNested()
  @Type(() => ProductCategory)
  @IsOptional()
  twoCategoryId?: ProductCategory | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}
export { ProductInfo };
