/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsInt, IsOptional, IsString, ValidateNested } from "class-validator";
import { ProductSPUInfoWhereUniqueInput } from "../../productSpuInfo/base/ProductSPUInfoWhereUniqueInput";
import { Type } from "class-transformer";
@InputType()
class ProductPicInfoCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  isMaster?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ossKey?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  picDesc?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  picOrder?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  picStatus?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  picUrl?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProductSPUInfoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductSPUInfoWhereUniqueInput)
  @IsOptional()
  @Field(() => ProductSPUInfoWhereUniqueInput, {
    nullable: true,
  })
  productId?: ProductSPUInfoWhereUniqueInput | null;
}
export { ProductPicInfoCreateInput };
